### ISSUE TITLE
"No BGAPI compatible device detected" when connecting to Muse via example_plot.py

### ISSUE THREAD

**Issue by bncuthbert** [merlin-neurotech/WizardHat#11]
This bug occasionally occurs on the master branch using Python 3.6.5 and Python 3.7.0. Current master is on `commit b72e3ff7f313eb715a24ebaf7b85bad021de7443`.

```
>>> python example_plot.py
WARNING: No module named 'pexpect'
Traceback (most recent call last):
  File "/Users/benc/dev/merlin/py3.6/lib/python3.6/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
OSError: [Errno 6] Device not configured: '/dev/cu.usbmodem1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benc/dev/merlin/py3.6/lib/python3.6/site-packages/pygatt/backends/bgapi/bgapi.py", line 159, in _open_serial_port
    timeout=0.25)
  File "/Users/benc/dev/merlin/py3.6/lib/python3.6/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/Users/benc/dev/merlin/py3.6/lib/python3.6/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 6] could not open port /dev/cu.usbmodem1: [Errno 6] Device not configured: '/dev/cu.usbmodem1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_plot.py", line 14, in <module>
    streamer = ble2lsl.Streamer(device)
  File "/Users/benc/dev/merlin/WizardHat/ble2lsl/ble2lsl.py", line 218, in __init__
    self.connect()
  File "/Users/benc/dev/merlin/WizardHat/ble2lsl/ble2lsl.py", line 268, in connect
    self._adapter.start()
  File "/Users/benc/dev/merlin/py3.6/lib/python3.6/site-packages/pygatt/backends/bgapi/bgapi.py", line 202, in start
    self._open_serial_port()
  File "/Users/benc/dev/merlin/py3.6/lib/python3.6/site-packages/pygatt/backends/bgapi/bgapi.py", line 170, in _open_serial_port
    "No BGAPI compatible device detected")
```

**Comment by bncuthbert** [comment]
macOS High Sierra 10.13.6
